# Generated by Django 3.2.6 on 2021-10-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='picked',
            field=models.BooleanField(default=False),
        ),
    ]
